// Single source of truth for all category definitions.
// Imported by QuickInput, EditTransactionSheet, TransactionHistory, Dashboard.

export const CATEGORIES = [
  {
    id:        'Meals'      as const,
    viName:    'Ăn uống sinh hoạt',
    label:     'Ăn uống',
    icon:      'restaurant',
    hex:       '#2e7d32',
    bg:        'bg-[#eef6ef]',
    iconBg:    'bg-[#c8e6c9]/60',
    iconColor: 'text-[#2e7d32]',
    textColor: 'text-[#1b5e20]',
    ringColor: 'ring-[#66bb6a]',
    selBg:     '#c8e6c9',
  },
  {
    id:        'Shopping'   as const,
    viName:    'Mua hàng',
    label:     'Mua hàng',
    icon:      'shopping_bag',
    hex:       '#e65100',
    bg:        'bg-[#fff3e0]',
    iconBg:    'bg-[#ffe0b2]/60',
    iconColor: 'text-[#e65100]',
    textColor: 'text-[#bf360c]',
    ringColor: 'ring-[#ffa726]',
    selBg:     '#ffe0b2',
  },
  {
    id:        'Transport'  as const,
    viName:    'Phương tiện di chuyển',
    label:     'Di chuyển',
    icon:      'directions_car',
    hex:       '#006064',
    bg:        'bg-[#e0f7fa]',
    iconBg:    'bg-[#b2ebf2]/60',
    iconColor: 'text-[#006064]',
    textColor: 'text-[#004d40]',
    ringColor: 'ring-[#26c6da]',
    selBg:     '#b2ebf2',
  },
  {
    id:        'Compulsory' as const,
    viName:    'Chi tiêu bắt buộc',
    label:     'Bắt buộc',
    icon:      'receipt_long',
    hex:       '#455a64',
    bg:        'bg-[#eceff1]',
    iconBg:    'bg-[#cfd8dc]/60',
    iconColor: 'text-[#455a64]',
    textColor: 'text-[#263238]',
    ringColor: 'ring-[#78909c]',
    selBg:     '#cfd8dc',
  },
  {
    id:        'Fun'        as const,
    viName:    'Đi chơi',
    label:     'Vui chơi',
    icon:      'celebration',
    hex:       '#1565c0',
    bg:        'bg-[#e3f2fd]',
    iconBg:    'bg-[#bbdefb]/60',
    iconColor: 'text-[#1565c0]',
    textColor: 'text-[#0d47a1]',
    ringColor: 'ring-[#42a5f5]',
    selBg:     '#bbdefb',
  },
  {
    id:        'Invest'     as const,
    viName:    'Đầu tư',
    label:     'Đầu tư',
    icon:      'trending_up',
    hex:       '#6a1b9a',
    bg:        'bg-[#f3e5f5]',
    iconBg:    'bg-[#e1bee7]/60',
    iconColor: 'text-[#6a1b9a]',
    textColor: 'text-[#4a148c]',
    ringColor: 'ring-[#ab47bc]',
    selBg:     '#e1bee7',
  },
  {
    id:        'Savings'    as const,
    viName:    'Tiết kiệm',
    label:     'Tiết kiệm',
    icon:      'savings',
    hex:       '#558b2f',
    bg:        'bg-[#f9fbe7]',
    iconBg:    'bg-[#f0f4c3]/60',
    iconColor: 'text-[#558b2f]',
    textColor: 'text-[#33691e]',
    ringColor: 'ring-[#aed581]',
    selBg:     '#dcedc8',
  },
  {
    id:        'Income'     as const,
    viName:    'Thu nhập',
    label:     'Thu nhập',
    icon:      'payments',
    hex:       '#880e4f',
    bg:        'bg-[#fce4ec]',
    iconBg:    'bg-[#f8bbd0]/60',
    iconColor: 'text-[#880e4f]',
    textColor: 'text-[#4a0072]',
    ringColor: 'ring-[#ec407a]',
    selBg:     '#f8bbd0',
  },
  {
    id:        'Other'      as const,
    viName:    'Chi tiêu khác',
    label:     'Khác',
    icon:      'more_horiz',
    hex:       '#f57f17',
    bg:        'bg-[#fffde7]',
    iconBg:    'bg-[#fff9c4]/60',
    iconColor: 'text-[#f57f17]',
    textColor: 'text-[#e65100]',
    ringColor: 'ring-[#ffca28]',
    selBg:     '#fff9c4',
  },
] as const

export type CategoryId = (typeof CATEGORIES)[number]['id']

// Lookup maps derived from CATEGORIES — no duplication
export const CAT_BY_VI = Object.fromEntries(CATEGORIES.map(c => [c.viName, c]))
export const CAT_BY_ID = Object.fromEntries(CATEGORIES.map(c => [c.id, c]))

// Note suggestions shared between QuickInput and EditTransactionSheet
export const NOTE_SUGGESTIONS: { label: string; keys: string[] }[] = [
  { label: 'Ăn sáng',          keys: ['an sang'] },
  { label: 'Ăn trưa',          keys: ['an trua'] },
  { label: 'Ăn tối',           keys: ['an toi'] },
  { label: 'Ăn vặt',           keys: ['an vat'] },
  { label: 'Ăn ngoài',         keys: ['an ngoai'] },
  { label: 'Cà phê',           keys: ['ca phe', 'cf'] },
  { label: 'Trà sữa',          keys: ['tra sua', 'ts'] },
  { label: 'Sinh tố',          keys: ['sinh to'] },
  { label: 'Nước uống',        keys: ['nuoc uong', 'nuoc'] },
  { label: 'Phở',              keys: ['pho'] },
  { label: 'Bún',              keys: ['bun'] },
  { label: 'Cơm',              keys: ['com'] },
  { label: 'Bánh mì',          keys: ['banh mi', 'banh'] },
  { label: 'Bánh ngọt',        keys: ['banh ngot'] },
  { label: 'Đổ xăng',         keys: ['do xang', 'do', 'xang'] },
  { label: 'Grab',             keys: ['grab'] },
  { label: 'Taxi',             keys: ['taxi', 'ta'] },
  { label: 'Xe buýt',          keys: ['xe buyt', 'xe'] },
  { label: 'Gửi xe',           keys: ['gui xe'] },
  { label: 'Siêu thị',        keys: ['sieu thi', 'sieu'] },
  { label: 'Winmart',          keys: ['winmart', 'win'] },
  { label: 'Tạp hóa',         keys: ['tap hoa'] },
  { label: 'Mua hàng',        keys: ['mua hang', 'mua'] },
  { label: 'Quần áo',         keys: ['quan ao'] },
  { label: 'Giày dép',        keys: ['giay dep'] },
  { label: 'Mỹ phẩm',         keys: ['my pham'] },
  { label: 'Tiền nhà',        keys: ['tien nha'] },
  { label: 'Tiền điện',       keys: ['tien dien'] },
  { label: 'Tiền nước',       keys: ['tien nuoc'] },
  { label: 'Tiền internet',   keys: ['tien internet', 'inet'] },
  { label: 'Tiền điện thoại', keys: ['tien dien thoai'] },
  { label: 'Bảo hiểm',        keys: ['bao hiem'] },
  { label: 'Xem phim',        keys: ['xem phim', 'phim'] },
  { label: 'Karaoke',         keys: ['karaoke', 'kara'] },
  { label: 'Du lịch',         keys: ['du lich'] },
  { label: 'Gym',             keys: ['gym'] },
  { label: 'Đám cưới',        keys: ['dam cuoi', 'dam'] },
  { label: 'Momo',            keys: ['momo', 'mo'] },
  { label: 'ZaloPay',         keys: ['zalopay', 'zalo'] },
  { label: 'Lương',           keys: ['luong'] },
  { label: 'Thưởng',          keys: ['thuong'] },
  { label: 'Freelance',       keys: ['freelance', 'free'] },
  { label: 'Thuốc',           keys: ['thuoc'] },
  { label: 'Khám bệnh',       keys: ['kham benh', 'kham'] },
]
